App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = 'App_Blog'

urlpatterns= [

     path('', views.BlogList.as_view(), name='blog_list'),
     path('write/', views.CreateBlog.as_view(), name='create_blog'),
     path('details/<slug:slug>/', views.blog_details, name='blog_details'),





]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns= [

     path('signup/', views.sign_up, name='sign_up'),
     path('login/', views.login_page, name='login'),
     path('logout/', views.logout_user, name='logout'),
     path('profile/', views.profile, name='profile'),
     path('change-profile/', views.user_change, name='user_change'),
     path('password/', views.pass_change, name='pass_change'),
     path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
     path('change-picture/', views.change_pro_pic, name='change_pro_pic'),


]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index'),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name='put a title')
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name='what is on your mind!')
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.blog_title

    #def get_absolute_url(self):
     #   return reverse('App_Blog:blog_details', kwargs={'slug': self.slug})


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-comment_date',)

    def __str__(self):
        return self.comment



class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_user')

    def __str__(self):
        return self.user + "likes" + self.blog

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='Email Address', required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')


class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic', ]

App_Blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView, View, TemplateView, UpdateView,\
    DeleteView
from App_Blog.models import Blog, Comment, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid



class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'App_Blog/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image',)

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))


class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'



@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)

    return render(request, 'App_Blog/blog_details.html', context={'blog': blog})

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, UserProfileChange, ProfilePic

# Create your views here.
def sign_up(request):
    form = SignUpForm()
    registered = False

    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True


    dict = {'form': form, 'registered': registered}
    return render(request, 'App_Login/signup.html', context=dict)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

    return render(request, 'App_Login/login.html', context={'form':form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)

    return render(request, 'App_Login/change_profile.html', context={'form': form})

@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            #form = PasswordChangeForm(current_user)
            changed = True

    return render(request, 'App_Login/pass_change.html', context={'form': form, 'changed': changed})

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request, 'App_Login/pro_pic_add.html', context={'form': form})



@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request, 'App_Login/pro_pic_add.html', context={'form': form})

My_Blog_Project/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect


def Index(request):
    return HttpResponseRedirect(reverse('App_Blog:blog_list'))

templates/App_Blog/blog_details.html
{% extends 'Base.html' %}

{% block title_block %}
{{blog.blog_title}}
{% endblock %}

{% block body_block %}
<div class="row">
    <div class="col-sm-6">
        <h2>{{blog.blog_title}}</h2>
        <i><h3>Posted By: @{{blog.author}}</h3></i>
        <i><h6>Published On: {{blog.publish_date}}</h6></i>
        <i><h6>Updated On: {{blog.update_date}}</h6></i>
    </div>

    <div class="col-sm-6">
        <img src="/media/{{blog.blog_image}}" width="100%">

    </div>
       <p>{{blog.blog_content|linebreaks}}</p>
</div>


{% endblock %}

templates/App_Blog/blog_list.html
{% extends 'Base.html' %}
{% load custom_filters %}
{% block title_block %}
Home
{% endblock %}


{% block body_block %}

{% for blog in blogs %}
<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>

<div class="row">
    <div class="col-sm-4">
        <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}"
        width="100%">
    </div>

    <div class="col-sm-8">
        <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'App_Blog:blog_details'
         slug=blog.slug %}">Read More</a>
        </p>

        <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
    </div>
</div>
<hr>
{% endfor %}

{% endblock %}

templates/App_Blog/create_blog.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
Create Blog
{% endblock %}

{% block body_block %}
<h2>Create Your Blog:</h2>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}

    <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>

{% endblock %}

templates/App_Blog/edit_blog.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}

{% endblock %}

{% block body_block %}


{% endblock %}

templates/App_Blog/my_blogs.html
{% extends 'Base.html' %}

{% block title_block %}

{% endblock %}

{% block body_block %}


{% endblock %}

templates/App_Login/change_profile.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Change Profile
{% endblock %}

{% block body_block %}
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}

<button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>

{% endblock %}

templates/App_Login/login.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Login
{% endblock %}

{% block body_block %}
<h2>Login:</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}

<button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>

{% endblock %}

templates/App_Login/pass_change.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Change Password
{% endblock %}

{% block body_block %}

{% if changed %}
<div class="alert alert-success">
    Password Change Successfully!!
</div>
{% endif %}
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}

<button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>

{% endblock %}

templates/App_Login/pro_pic_add.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Profile
{% endblock %}

{% block body_block %}
<h2>Add your Profile Picture:</h2>
<form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}

<button type="submit" class="btn btn-success btn-sm">Add</button>
</form>

{% endblock %}

templates/App_Login/profile.html
{% extends 'Base.html' %}
{% block title_block %}
Profile
{% endblock %}

{% block body_block %}
<h2>Your Profile:</h2>
{% if user.user_profile %}
<img src='/media/{{ user.user_profile.profile_pic }}' class="rounded-circle" width="100px">
<br>
<a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">change profile pic</a>
<br>
<br>
{% else %}
<img src='/media/profile_pics/avatar.png' class="rounded-circle" width="100px">
<br>
<a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">change profile pic</a>
{% endif %}
<br>
<br>
<p>Username: {{ user.username }}</p>
<p>Name: {{ user.first_name }} {{ user.last_name }}</p>
<p>Email: {{ user.email }}</p>
<br>
<a href="{% url 'App_Login:user_change' %}" class="btn btn-warning btn-sm">Change Profile Info</a>

{% endblock %}

templates/App_Login/signup.html
{% extends 'Base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Create new account
{% endblock %}

{% block body_block %}

{% if registered %}
<div class="alert alert-success">
    Account created successfully! <a href="{% url 'App_Login:login' %}">Login here</a>
</div>
{% else %}
<h2>Create new Account:</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
<button type="submit" class="btn btn-success btn-sm">Create Account</button>

</form>
<br>
<p>Already have an account? <a href="{% url 'App_Login:login' %}">Login here</a></p>
{% endif %}


{% endblock %}

templates/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <title>{% block title_block %} Blog {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}"><img src="/media/blog1.png" width="50px"></a>
      </li>
      {% if user.is_authenticated %}
    <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbardrop" data-bs-toggle="dropdown">
            @{{user.username}}
        </a>
          <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write</a>

              <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
              <hr>
              <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>

          </div>

    </div>

      {% else %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:sign_up' %}">SignUp</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
      </li>
      {% endif %}
  </ul>

</nav>

<div class="container" style="padding-top:20px">
    {% block body_block %}

    {% endblock %}
</div>


</body>
</html>